### ISSUE TITLE
GPL-413 BUG - 2D barcodes too big for label

### ISSUE THREAD

**Issue by rl15** [sanger/labwhere#114]
**Describe the bug**
See image - "the barcode doesn’t look as square as it should be, this also wouldn’t scan. " Danni W. (Friday, 17 April 2020 at 14:07)

**RT Ticket Number**
Was fixed in RT 67694 resolved, backlog item declared done & released in sprint #133, Aug 2019

**To Reproduce**
Steps to reproduce the behaviour:
Print 2D barcode from LabWhere
Cant scan barcode

**Expected behaviour**
Can scan 2D barcode

**Comment by rl15** [comment]
![LabWher_2D_barcodes_bigly_IMG_6268](https://user-images.githubusercontent.com/7222395/79579946-31744100-80c0-11ea-8f16-4cdac2e3a0fe.jpg)

**Comment by khelwood** [comment]
Caused by the template not specifying one_cell_width so the PMB defaulted to something too large to fit. I've updated the template in the PMB database so hopefully this is OK now.
