### ISSUE TITLE
GPL-479 empty a container in LabWhere presto-hay

### ISSUE THREAD

**Issue by rl15** [sanger/labwhere#125]
**User story**
GPL-479 | As lead for SM (Danni W) I would like a feature to empty a container as a single step, rather than scanning each barcoded labware out as working at -20 is wretched

**Who the primary contacts are for this story**
Rich L
Rich C
Danni W
Keith A

**Draft Acceptance criteria**

Note Scanning/ out screen has process model 'Location barcode (Leave blank to scan out). Options required how to make this work.
...
Button on screen [Empty container of all Labware]
Nice to have: Audit shows that were not scanned out, but show as removed with this feature

**Additional context**
Part of difficult process design for Sampling strategy for Lighthouse labs and specifically auditing whats in a box once opened.

**Comment by stevieing** [comment]
Using the scan page requires the labware to be scanned in. Time consuming and they might miss some.
