### ISSUE TITLE
GPL-516 Update lighthouse boxes to true locations

### ISSUE THREAD

**Issue by rl15** [sanger/labwhere#133]
**User story**
GPL-516 | As SM lead (Danni) I need the lighthouse boxes and their contents that did not move by by scanning (see GPL-504) to be given their true location so we can pick samples and follow outbreaks in a timely manner

**Who are the primary contacts for this story**
Danni W
Stephen I
Rich L

**Acceptance criteria**
To be considered successful the solution must allow:
Write scrip to 
a. find all lighthouse box barcodes stored in their creation directory 
b. and for those box barcodes find parent location of any *labwares* that *is* the box barcode 
c. Move box (and any plates it contains) to box barcodes labwares parent location
d. Remove any box barcode Labwares barcodes from parent location
d. test script in UAT, Danni can run report if ok
e. Backup data in production, save state to (RT?)
f. Run script in production

**Comment by KatyTaylor** [comment]
Preliminary queries investigating the data to be changed:

```
-- the dodgy 'labwares' to remove - 174
SELECT lw.barcode, lw.location_id, loc.name, loc.parentage, lw.created_at
FROM labwares lw
JOIN locations loc ON lw.location_id = loc.id
WHERE lw.barcode LIKE 'lw-%'
	AND loc.parentage LIKE '%Reefer%'
ORDER BY created_at DESC;

-- the locations to be moved - also 174 :)
SELECT *
FROM locations loc
WHERE barcode IN (
	SELECT lw.barcode
	FROM labwares lw
	JOIN locations loc ON lw.location_id = loc.id
	WHERE lw.barcode LIKE 'lw-%'
		AND loc.parentage LIKE '%Reefer%'
);

-- move the above locations so that their 'internal_parent_id' is the location of the labwares above (?)
-- then delete the dodgy 'labwares'
```

**Comment by stevieing** [comment]
I think that is pretty much it.

I think you can use Railsy stuff to make the SQL easier but I guess you just like using SQL!

Further note that I have from a conversation with Danni:
Remove all labware in shelfs in Reefers 1 - 5

After Danni has run the report.

We need to run the script immediately after Danni has run the report.

Fro each shelf in each rack in each reefer

Get the labware barcode > get the location > move that box into the shelf and then remove the labware.

**Comment by KatyTaylor** [comment]
Putting some test code here for now, as not sure where to put it:

```
# *********** A script to test the rake task: **************
# Create a Lighthouse box, with a plate in it
box = UnorderedLocation.create!(name: 'box 1', location_type: LocationType.first, parent: Location.first)
plate = Labware.create!(barcode: 'plate_1', location: box)

# Create a shelf in a reefer, to where we want to move the box
reefer = Location.create!(name: 'reefer 1', location_type: LocationType.first, parent: Location.find(2))
shelf = Location.create!(name: 'shelf 1', location_type: LocationType.first, parent: reefer)
# Create a labware, which we accidentally created when we tried to move the box previously
box_labware = Labware.create!(barcode: box.barcode, location: shelf)

# Run script here

# Check that box still contains plate
box.labwares.count # should be 1
box.labwares.first.barcode # should be 'plate_1'

# Check that reefer contains box
shelf.children.count # should be 1
shelf.children.first.barcode # should be box.barcode

# Check that box_labware was deleted
Labware.find_by(barcode: box.barcode) # should return nothing
```
