### ISSUE TITLE
GPL-468 record plate reception via box manifest upload

### ISSUE THREAD

**Issue by rl15** [sanger/labwhere#140]
**User story**
GPL-468 | As lead for SM (Danni W) I would like to be able to import into LabWhere a box manifest supplied by the lighthouse labs into record RNA plates on site as they cant be scanned in individually as they will defrost degrading the RNA
-- | --

**Who the primary contacts are for this story**
Danni W
Rich C
Stephen I
Katie T

**Acceptance criteria**
To be considered successful the solution must allow:
- The upload of a box manifest file into Labware to record declared plates in a given box
- Container specified in file (Aldenery Park file is the de facto standard)
- Update audit of LabWhere, with new state {Declared} 
    - NB Current states {Scanned, destroyed} 

** Context**
General process flow

1. Sanger send empty, barcoded box to a lighthouse lab [Box empty]
2. Lighthouse ships box back with ~80 plates in it
3. SM scan box (barcode) into location (a reefer shelf)
4. SM/SSR upload box manifest file [Box contains 'declared' labware]
4.1 _NB labware now have locations so institute **believes** they are on site see GPL-472)_
6. SM empty box (GPL-479) [Box empty]
7. SM scan plates back into box [Box contains 'scanned' labware]
_7.1 institute verifies labwareare on site_

Please see https://ssg-confluence.internal.sanger.ac.uk/x/iKMKBg 

**Historical discussions**

- Moved responsibility back to LabWhere following further discussion on 20th May @10 (Email dated Wednesday, 20 May 2020 at 11:17 

- Re comment from @KatyTaylor is it actually a downstream file that will be uploaded into asset audits.
- Given that scanning plates is not itself the bottleneck, but rather performance of the response/import. Would it make sense to perform all imports asynchronously. (And would this eliminate the need for actually processing a file?)

**Additional context**
See https://ssg-confluence.internal.sanger.ac.uk/x/iKMKBg (figure 3.1)

**Comment by stevieing** [comment]
Just to confirm what was agreed yesterday with regard to the above story:
- We will allow users to upload a csv manifest to Labwhere
- This manifest will contain two columns. Column 1 will contain the location barcode (box) and column 2 will contain the labware barcode (plate)
- The location must be a location that already exists in Labwhere
- Each labware will have an audit record attached “uploaded from manifest”
- Users must still scan their user barcode
