### ISSUE TITLE
GPL-548 BUG - When I search for some locations in Labwhere it returns 0 results

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#152]
**Describe the bug**
I think the search box in labwhere has stopped working.

For example when I search for "UK Biocentre box GSW 96" it returns 0 results but this is location with labwhere in it. As there are now so many light house locations this search function is important to finding samples. Without this I will have to search through every location until I find the box I'm looking for.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page labwhere home page
2. fill in search with "UK Biocentre box GSW 96"
2. Click on button search
3. See 0 results returned

**Expected behaviour**
results should be returned
**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by stevieing** [comment]
The reason why this was happening was because there was an extra space in the location name. There is however a bug when you add a space to the search term which returns nothing but it seems like the search returns no results. It is picking up a previous search which didn't work.

**Comment by rl15** [comment]
Agreed plan from 9;30 standup

1. Remove double spaces from Location names of impacted Labware 
2. Assert if double spacing is caused by user of bug
3. Agree if will trim out double spaces in location names to prevent from happening in future (or warn on creation?
