### ISSUE TITLE
GPL-578 Expose Labware & its first and last location to faculty

### ISSUE THREAD

**Issue by rl15** [sanger/labwhere#181]
**User story**
GPL-578 | As PAM informatics leads (Rob K & Ian W) we would like to know when a LH RNA plate is on site to support 'end to end' reporting

Note while this item is for PAM and specifically the Heron project, there is wider benefit in exposing in MLWH physical location of a barcoded container to faculty informatics teams.

**Who are the primary contacts for this story**
Rob K (PAM)
Ian W (PAM)
Rich L
Neil S

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] new table in MLWH labware_emporium
- [ ] Draft design Options
Option 1: Columns, container barcode, timestamp first scanned in (created), location when first scanned in, scanned or file upload?,  last scanned in date (updated) and location at updated in time [Update row on new scan events]
Option 2: Columns Barcode, User, location, updated at, scanned or file upload? [new row for each scan event] This option would give us a audit record also.

**Assumptions**
Any update to the MLWH is done asynchronously from GUI interaction.

**Context**
Two key questions that faculty would like to answer

Q1. Is my sample (in a container) here yet? / When did it arrive?
Q2. Where is it now?

**Comment by KatyTaylor** [comment]
Things to remember when deploying:
- [ ] Have correct version of deployment project (with new bunny config) checked out 
- [ ] Deploy Events Warehouse
- [ ] ssh onto Events Warehouse host and run rake task `dictionaries:update`, to add new event types
- [ ] Deploy LabWhere, making sure it runs the migrations
- [ ] ssh onto LabWhere host and run rake task `migration:create_uuids`, to populate new uuid columns

Scenarios to test in UAT (after each, check the appropriate event(s) are created in the Events Warehouse):
- [ ] Scan a new labware into LabWhere
- [ ] Re-scan the same labware into a different location in LabWhere
- [ ] Upload some labwares with a csv into LabWhere
- [ ] Empty a location in LabWhere using the page for this
- [ ] Scan a labware into LabWhere Reception, in Sequencescape
