### ISSUE TITLE
GPL-626 BUG - changing location type

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/labwhere#184]
**Describe the bug**
I am able to edit an UnorderedLocation so that it has coordinates, and is therefore just like an OrderedLocation. However, when I do this it does not change type from Unordered to Ordered.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page 'Configure -> Locations -> Add new location'
2. Fill in details, leaving 'Has Co-ordinates' unchecked
3. Click 'Create Location'
4. Verify that a Location of type 'UnorderedLocation' has been created in the locations table in the database.
5. Go to 'Add new location' page again (step 1)
6. Fill in details, checking 'Has Co-ordinates' and filling in Rows and Columns
7. Click 'Create Location'
8. Verify that a Location of type 'OrderedLocation' has been created in the locations table in the database.
9. Find the barcode of the first Location you created and search for it in the search box.
10. Click the edit / pencil and paper symbol next to the search result.
11. Check  'Has Co-ordinates' and fill in Rows and Columns.
12. Click 'Update Location'
13. Verify that the type of the Location in the database has not changed.

**Expected behaviour**
The update location screen should prevent users from changing whether or not Locations have coordinates. 

(If it did allow it, it should deal with it properly, by changing the Location type. This would be problematic though because any labware contained within that location might or might not have the coordinates filled in.)

**Comment by Chris-Friend** [comment]
@KatyTaylor you outline the desired behaviour for UnorderedLocations: that it should not be possible to add co-ordinates on Edit.

Should similar behaviour exist for OrderedLocations? i.e. being unable to uncheck the Has Co-ordinates box? With co-ordinates existing being handled by the validation mentioned in Bug GPL-627?

**Comment by KatyTaylor** [comment]
Hi @Chris-Friend 
Good point, yes it should work the same the other way round. So, you should not be able to uncheck the Has Co-ordinates box when editing an OrderedLocation.

**Comment by alexperrin1** [comment]
Tested in UAT - looks good, though when I tried to delete one of the test locations I had created (`ordered-location-627`) , the deletion wouldn't work. Unsure if this was an existing issue, or as a result of the recent bugfixes of this and GPL-627

**Comment by Chris-Friend** [comment]
Just locally tested the changes on this branch only in an attempt to duplicate the deletion issue: on adding new Ordered and Unordered locations, I am still able to delete them
