### ISSUE TITLE
GPL-647  BUG - silient failure of large box manifest uploads

### ISSUE THREAD

**Issue by rl15** [sanger/labwhere#197]
**Describe the bug**

GPL-647 | BUG: LabWhere: Box manifest upload may time out mostly boxes given location but not always - silent failure can lead to rework/ waste as identified in RT Hinxton #698920

**RT Ticket Number**
#698920
https://rt.sanger.ac.uk/Ticket/Display.html?id=698920&results=ea47a55513fe943a684852d76b58f4d7 

**To Reproduce**
Steps to reproduce the behaviour:
1. Upload large*1 box manifest
2. Click on button
3. See timeout error
4. Anecdotally even though there is error locations are created & updated typically. Occasionally it fails.

*1 Is not clear where the cut off is on large/

**Expected behaviour**
Error and no upload
No error and transaction load of all plate

**Work around?**
Discussed with operations (James M & Deb P) on 9th Sept, proposed work-around was to serch for first and last plate barcodes in LabWhere.

**Comment by stevieing** [comment]
Although this is a problem it was agreed up front with stakeholders that this would not be dealt with at the time due to the amount of work that needed to be done.

To fix it would require making the manifest upload asynchronous and having a delayed job.

**Comment by JamesGlover** [comment]
I'm still not entirely sure what happened to cause the original upload to fail silently. Most the validation happens upfront, although that doesn't exclude the possibility of other issues, like transient network problems. Without the VPN I can't check logs.

**Comment by JamesGlover** [comment]
PR with a number of performance improvements:
https://github.com/sanger/labwhere/pull/201
