### ISSUE TITLE
GPL-683 Reefer box counts

### ISSUE THREAD

**Issue by rl15** [sanger/labwhere#221]
**User story**
GPL-683 | As destruction stakeholders (Alan K & Tanya B) we would like a report detail box counts per reefer to understand when our five (5) reefers are approaching capacity 

**Who are the primary contacts for this story**
Alan K
Tanya B

**Acceptance criteria**
To be considered successful the solution must show

Table of 
Reefer name | Count of boxes

Where 
Reefer name is in set {Reefer 1, Reefer 2, Reefer 3, Reefer 4, Reefer 5} 
Count of boxes: Count barcodes items of type 'Box' (ignore racking & shelf hierarchy). 

**Questions**
Q> Box may be empty? - does this happen?

**Additional context**

**Comment by TWJW-SANGER** [comment]
Prototype query below on labwhere_production database. Note this only counts "locations" or containers not labware entities themselves

```SQL
USE labwhere_production;

SET @parent_depth := 2; -- how many levels down before we start counting children, reefers start at "Sanger / Reefer x"

SELECT  TRIM(SUBSTRING_INDEX(locations.parentage, "/", @parent_depth)) AS container
		, COUNT(locations.barcode) AS count_of_type
        FROM 
locations
JOIN
location_types ON location_types.id=locations.location_type_id

WHERE
deactivated_at IS NULL
AND location_types.name = "Box"  -- one of SELECT DISTINCT name FROM location_types, default to "Box"
AND locations.parentage LIKE "%Reefer%"  -- optional filter on reported locations

GROUP BY TRIM(SUBSTRING_INDEX(locations.parentage, "/", @parent_depth))
```

Produces:
```
container,count_of_type
"Sanger / Reefer 1",229
"Sanger / Reefer 2",233
"Sanger / Reefer 3",210
"Sanger / Reefer 4",241
"Sanger / Reefer 5",159
```

- [ ] Need to get current estimates of this
- [ ] Discuss how generic tableau report might work - user entering depth and what type to be counted

**Comment by TWJW-SANGER** [comment]
Can we make a more generic report by providing a view containing
- A count of locations of selected type
- From a level of depth AND / OR a search filter on the parent location name

Could we provide the Heron boxes in Reefer view as a default or template of the more generic report?

**Comment by ugleymatt** [comment]
In order to do % capacity we need an estimate on how many boxes a reefer can hold. For Dev purposes, I've set it at 260 based on a conversation with @TWJW-SANGER

**Comment by TWJW-SANGER** [comment]
After feedback:
* Capacity of reefer is 252 boxes
* Showing percentages and box counts on report

Report currently at bottom of:https://globalreporting.internal.sanger.ac.uk/#/views/LabWhere/LighthouseStorageDestruction?:iid=1

**Comment by TWJW-SANGER** [comment]
Agreement that Tableau report shows what is currently in LabWhere.
RT's open to correct data in LabWhere and actions with Reefer team to tidy up boxes that exist in LabWhere but not in reality.
This can be closed now.
