### ISSUE TITLE
GPL-684 Report boxes & plates in the reefers that can be destroyed

### ISSUE THREAD

**Issue by rl15** [sanger/labwhere#222]
**User story**
GPL-684 | As Heron SSR (James M) can I have a weekly report that returns list of box barcodes & their plate barcodes that contain samples with a date tested window to understand our destruction health

**Who are the primary contacts for this story**
James M
Sameena 

**Acceptance criteria**
TBD - see note below

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by rl15** [comment]
James M wrote (Monday, 5 October 2020 at 16:21)

Would it be possible for PSD to provide a report based on the following criteria? The original suggestion was to run this report once every two weeks on a Monday for Sameena to plan the work on the Tuesday. The frequency with which this report is run may actually need to be run on a weekly basis.
 
·         Would you be able to return a list of all boxes that contain only samples that have a “date tested” recorded as after the 8th of June but before the 24th August (as of today, this date should progress so that it is 6 weeks before the current date).
 
·         Could you list all of the plates that should be in these boxes.
 
·         The date of 8th of June will remain fixed unless it is decided by the current test on Historical samples that it is not worth retaining these samples.
 
·         If a box contains some samples that fall within the date range but others that fall outside the date range the whole box should not appear in the list.

**Comment by TWJW-SANGER** [comment]
Following meeting with Richard Rance & James Mack.

Jame Mack would like a report that could be run by volunteers at the reefer that produces a report of all box barcodes and contained plate barcodes currently in the reefers which can be destroyed.

This report should:
- Excludes **plates** which contain samples with a date test within a set of excluded date ranges (TBD)
- Excludes **plates** which contain Vaccine samples, with "VAC" prefixes on their Light house root_sample_id

The report format should be:

| Min Sample Date Tested | Max Sample Date Tested | Box Location | Box Barcode | Plate Barcode |
|-------------------------|---------------------------|-------------|--------------|----------------|
| 2020-09-20                   | 2020-09-27 |     Reefer 1 / R1 Racking 1 / Shelf 1 | lw-uk-biocentre-box-ap-60-14889 |  002327670 |

Ordered by **Box Location**

**Comment by TWJW-SANGER** [comment]
Prototype SQL code against MLWH
```sql
SELECT 
MIN(DATE(ls.date_tested)) AS min_date_tested
, MAX(DATE(ls.date_tested)) AS max_date_tested
, md.value AS box_location
, location.friendly_name AS box_barcode
, ls.plate_barcode AS plate_barcode

FROM mlwh_events.events e
JOIN mlwh_events.metadata md ON e.id = md.event_id -- This set of JOINS against labwhere destruction events

JOIN mlwh_events.roles labware_r ON e.id = labware_r.event_id
JOIN mlwh_events.subjects labware ON labware.id = labware_r.subject_id
JOIN mlwh_events.role_types labware_rt ON labware_r.role_type_id = labware_rt.id

JOIN mlwh_events.roles location_r on e.id = location_r.event_id
JOIN mlwh_events.subjects location ON location.id = location_r.subject_id
JOIN mlwh_events.role_types location_rt ON location_r.role_type_id = location_rt.id

-- make sure we're getting the last event for this plate to avoid
-- issues with plates being scanned in and then out of destroyed destination
JOIN
(
    SELECT 
    labware.friendly_name AS plate
    , MAX(e.occured_at) AS occured_at
    FROM mlwh_events.events e
    JOIN mlwh_events.metadata md ON e.id = md.event_id -- This set of JOINS against labwhere events

    -- plate / labware id
    JOIN mlwh_events.roles labware_r ON e.id = labware_r.event_id
    JOIN mlwh_events.subjects labware ON labware.id = labware_r.subject_id
    JOIN mlwh_events.role_types labware_rt ON labware_r.role_type_id = labware_rt.id

    WHERE e.lims_id='LABWHERE'
    AND labware_rt.key = 'labware'

    GROUP BY plate

) AS last_plate_event ON labware.friendly_name = last_plate_event.plate 
                      AND e.occured_at = last_plate_event.occured_at  -- this forces last labwhere event row for a given plate

-- join against lighthouse_sample table in mlwh 
-- not all plates have plate maps s
JOIN mlwarehouse.lighthouse_sample ls ON ls.plate_barcode=labware.friendly_name  

WHERE 
e.lims_id='LABWHERE'
AND labware_rt.key = 'labware'
AND location_rt.key = 'location'

AND md.key='location_info'
AND REPLACE(md.value, ' ', '') LIKE '%Reefer%'  -- find plates in reefers, need to remove spaces for LIKE to work

GROUP BY ls.plate_barcode

-- example date exclusion range for date_tested
HAVING 
NOT min_date_tested BETWEEN DATE("2020-08-24") AND DATE("2020-08-30")
AND NOT max_date_tested BETWEEN DATE("2020-08-24") AND DATE("2020-08-30")
AND NOT DATE("2020-08-24") BETWEEN min_date_tested AND max_date_tested -- check box range does contain excluded range
AND NOT DATE("2020-08-30") BETWEEN min_date_tested AND max_date_tested
```

**Comment by TWJW-SANGER** [comment]
Updating requirements in comments above following meeting on 9/11 on the reporting.

Decided that PHE changing dates/samples to preserve samples happen too frequently to be completed modelled by software.
The software should produce a report that enables a human SSR to apply the latest known exclusions based on Lighthouse Lab & date range.
In effect this means the report needs to include the Lighthouse Laboratory source of the box too.

**Comment by TWJW-SANGER** [comment]
Following further review of the report users would like:

* To only preserve positive vaccine samples (not negative ones)
* To prioritise destroying boxes which contain all plates that meet the destruction criteria

**Comment by TWJW-SANGER** [comment]
Additional requirement to preserve any samples with a test date before the 8th June 2020

**Comment by TWJW-SANGER** [comment]
Current tasks:

- [ ] Create view to contain vaccine sample selection logic in MLWH - decouple Matt from logic changes
- [ ] Confirm process for team responding to PHx preserve requests
- [ ] Confirm process for reefer team getting destruction lists (what happens if request comes in during destruction etc...)

**Comment by TWJW-SANGER** [comment]
Written up new component architecture & process flows following discussion here:
https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=111057405

**Comment by stevieing** [comment]
Closed as project is finished.
