### ISSUE TITLE
GPL-748 BUG - Events not being logged for labware in box when transferred to new location

### ISSUE THREAD

**Issue by neilsycamore** [sanger/labwhere#239]
mlwh_events is missing events where a box containing labware has it's location moved using
http://labwhere.psd.sanger.ac.uk/move_locations/new
The events recording the new location of the labwares (within the box) is not created

Relates to https://rt.sanger.ac.uk/Ticket/Display.html?id=705108
Missing labware events from in mlwh_events
[inconsitent_locations_in_mlwh_events.xlsx](https://github.com/sanger/sequencescape/files/5536575/inconsitent_locations_in_mlwh_events.xlsx)

**Comment by stevieing** [comment]
So just to be clear on this one. The labware (plate) itself does not move location it is the box that moves.

**Comment by stevieing** [comment]
Meeting planned for 11/12

**Comment by stevieing** [comment]
Meeting with @TWJW-SANGER. There are various issues which are beyond the scope of this story which will be dealt with separately.
The solution for moving boxes will be dealt with in this story. if a box is moved we will make sure that any labwares within that box will have an event created.
