### ISSUE TITLE
GPL-779 BUG - Discrepancy between locations in Labwhere and Warehouse

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#263]
**Describe the bug**
From the report it looks like there are items in LabWhere whose updated locations have not been transmitted to the MLWH Events tables.
This discrepancy seems to be related to messages not appearing in the warehouse. There is no pattern so it could be a load issue.

The issue happens sporadically (maybe once every two months) and seems to appear for a short time (from a few seconds to few minutes) where movements in labwhere are not recorded in the MLWH events database.

This effects the ability to report on things like plate destruction from the MLWH Events database and could impact CoTrack and Heron reporting.

**RT Ticket Number**
705108

**To Reproduce**
Currently the behaviour can not be reproduced.

We should think about 
* Trying to narrow down the problem (are messages being sent by LabWhere? are messages being received by MLWH? consumers?)
* Logging & catching the problem as it happens
* Consistency checks or tripwires 
* Test systems that we can stress / fuzz to try to induce failure
* Something else....

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Additional context**
To generate a set of differences between MLWH events and LabWhere see attached zip file and instructions.
[cmp_labwhere_mlwh_locations.zip](https://github.com/sanger/labwhere/files/5782374/cmp_labwhere_mlwh_locations.zip)

Currently there are 221 items with incorrect locations in the MLWH Events tables.

Suggested course of action:
1. Check logs on warehouse server to see if messages were received
2. Create dedicated messaging queue for labwhere
3. Add loggin either or both sides to record status of messages.

**Comment by TWJW-SANGER** [comment]
I'm afraid this is still happening intermittently.

Last Labware move missing a MLWH event is 2021-01-28 12:20:29

Attaching full list of differences.
[differences_2021-01-28.csv.zip](https://github.com/sanger/labwhere/files/5887911/differences_2021-01-28.csv.zip)

**Comment by stevieing** [comment]
Moving to done as this will now be done as a monthly RT ticket.

**Comment by stevieing** [comment]
Clsoed as no longer needed. No longer using the events.
