### ISSUE TITLE
GPL-792 As a Reefer Team Manager (Bart & Sameena) I would like to be able to restrict LabWhere users who can scan boxes into the Mystery Box location in the Reefer Cabin

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/labwhere#266]
**User story**
As a Reefer Team Manager (Bart & Sameena) I would like to be able to restrict LabWhere users who can scan boxes into the Mystery Box location in the Reefer Cabin

**Who are the primary contacts for this story**
Sameena I
Bart S
Danni W

**Acceptance criteria**
- [x] Add a new user role (Technical Admin), which will not have complete admin permission but can move locations
- [x] Add a flag to location type as to whether it can be moved this will default to not allowed to be moved by standard users
- [ ] Have an allow list of location types which can be moved by standard users (redundant, no scientist/standand user can move locations)
- [ ] Bart & Sameena to have the ability to confer permission on LabWhere users
- [ ] Current Reefer teams LabWhere permissions to be reviewed and updated - SQL below, emailed/Slacked Danni (danni has permissions to update herself)

**Dependencies**
None

**Additional context**
The mystery box location is called "Mystery Heron Boxes" with barcode lw-mystery-heron-boxes-18920
Boxes that exist in LabWhere but not in reality are moved here so that:
* Reefer team can work out what's happened
* They are not included in the various reports that look at the contents of the reefers

**Comment by harrietc52** [comment]
Current Reefer teams LabWhere permissions to be reviewed and updated
`SELECT u.login, u.type, t.name,
CASE WHEN status = 0 THEN 'Active'
WHEN status = 1 THEN 'Inactive'
END AS status
FROM users AS u
JOIN teams AS t 
ON u.team_id=t.id
;`
