### ISSUE TITLE
GPL-789 Improve LabWhere for the Reefer team who currently record box movements offline in the reefers and then validate and upload to LabWhere later. 

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/labwhere#268]
**Description**
Research possible improvements to LabWhere and/or the Reefer team processes to improve the accuracy of the data stored in LabWhere.

**Who the primary contacts are for this work**
Sameena I
Bart S
Danni W

**Knowledge or Stake holders**
Mark J

**Additional context or information**
No or limited wifi inside the reefers.
Standard laptops have limited battery life in reefers
Reefer team can only spend a maximum of 20 mins inside a reefer

WiFi connectivity is currently being investigated for inside the Reefers by IT (Mark J)
Improved hardware currently being investigated.

Currently reefer team performing some kind of secondary validation before uploading box movements too LabWhere. We should establish what this validation is and what validation is needed.
![Sample Management and Portering v 1](https://user-images.githubusercontent.com/519327/104012386-a2f0a400-51a7-11eb-8b46-7c9964b6c917.jpg)

**Comment by stevieing** [comment]
Following the meeting on 05/01 set up a meeting to draw out the process and come up with the functionality necessary to complete the task.

**Comment by stevieing** [comment]
Productive meeting on 19/01. Todo:
- create process map (Harry / Steve)
- write up stories

**Comment by stevieing** [comment]
Closed as no longer needed.
