### ISSUE TITLE
GPL-787 BUG - Uploading an incorrect csv to the 'Upload Labware' tab creates labware entity with same the barcode as an existing location

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/labwhere#270]
**Describe the bug**
By uploading an incorrect csv file it is possible to create labware entries with barcodes that match existing locations.

**RT Ticket Number**
N/A

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a labware location for example _lw-tw-test-box-1-3701_
2. Create another labware location for example _lw-heron-boxes-destroyed-3700_
3. Upload a csv to http://uat.labwhere.psd.sanger.ac.uk/upload_labware/new of the form

```csv
Location,Labware,Position
lw-tw-test-box-1-3701,lw-heron-boxes-destroyed-3700,1
```

You will find a new piece of labware created under lw-tw-test-box-1-3701 with the same barcode as the existing location

**Expected behaviour**
I would expect the upload to fail and user to be informed of that the location column in their csv contains barcodes of locations.

**Screenshots**
<img width="863" alt="Screenshot 2020-12-17 at 16 58 13" src="https://user-images.githubusercontent.com/66008413/102518407-275c7500-4089-11eb-9d48-0b406e6ed449.png">

**Desktop (please complete the following information):**
Mac, Safari & Chrome

**Additional context**
This might explain some of the strange data in the reefer

**Comment by TWJW-SANGER** [comment]
More context:
I can find 23 pieces of labware in the reefers that have barcodes belonging to locations (boxes) but almost certainly don't exist.
This is skewing the reporting of reefer capacity.

List below generated by the following SQL
```sql
SELECT 
location_types.name AS location_type, 
labwares.barcode AS duplicate_barcode,
labware_loc.parentage AS duplicate_labware_location
FROM labwares
JOIN locations ON locations.barcode=labwares.barcode
JOIN location_types ON location_types.id=locations.location_type_id
JOIN locations labware_loc ON labware_loc.id=labwares.location_id
WHERE labware_loc.parentage LIKE '%Car park%'
```

```
location_type,duplicate_barcode,duplicate_labware_location
Box,lw-uk-biocentre-box-ap-201-16108,"Sanger / Reefer 1 / Car park A / R1 Racking 14"
Box,lw-uk-biocentre-box-ap-202-16109,"Sanger / Reefer 2 / Car park A / R2 Racking 13"
Box,lw-ap-replacement-10-16365,"Sanger / Car park A / Reefer 5 / R5 Racking 9 / Shelf 2"
Box,lw-ap-replacement-13-16368,"Sanger / Reefer 1 / Car park A / R1 Racking 6"
Box,lw-ap-replacement-20-16375,"Sanger / Reefer 5 / Car park A / R5 Racking 13 / Shelf 1"
Box,lw-lighthouse-cherrypicks-done-92-16820,"Sanger / Car park A / Reefer 5 / R5 Racking 9 / Shelf 2"
Box,lw-uk-biocentre-box-gsw-310-17631,"Sanger / Reefer 2 / Car park A / R2 Racking 13"
Box,lw-uk-biocentre-box-ap-608-18257,"Sanger / Reefer 2 / Car park A / R2 Racking 13"
Box,lw-uk-biocentre-box-ap-609-18258,"Sanger / Reefer 2 / Car park A / R2 Racking 13"
Box,lw-ap-replacement-33-18510,"Sanger / Reefer 1 / Car park A / R1 Racking 7"
Box,lw-ap-replacement-34-18511,"Sanger / Reefer 1 / Car park A / R1 Racking 14"
Box,lw-lh-replacement-1-18771,"Sanger / Reefer 1 / Car park A / R1 Racking 7"
Box,lw-lh-replacement-2-18772,"Sanger / Reefer 1 / Car park A / R1 Racking 9"
Box,lw-lh-replacement-3-18773,"Sanger / Reefer 1 / Car park A / R1 Racking 2"
Box,lw-lh-replacement-4-18774,"Sanger / Reefer 2 / Car park A / R2 Racking 14"
Box,lw-lh-replacement-5-18775,"Sanger / Reefer 2 / Car park A / R2 Racking 13"
Box,lw-lh-replacement-6-18776,"Sanger / Reefer 2 / Car park A / R2 Racking 13"
Box,lw-lh-replacement-9-18779,"Sanger / Reefer 2 / Car park A / R2 Racking 14"
Box,lw-lh-replacement-10-18780,"Sanger / Reefer 1 / Car park A / R1 Racking 9"
Box,lw-lh-replacement-11-18781,"Sanger / Reefer 2 / Car park A / R2 Racking 13"
Box,lw-lh-replacement-12-18782,"Sanger / Reefer 1 / Car park A / R1 Racking 1"
Box,lw-lh-replacement-14-18784,"Sanger / Reefer 1 / Car park A / R1 Racking 5"
Box,lw-lh-replacement-15-18785,"Sanger / Reefer 1 / Car park A / R1 Racking 7"
```

**Comment by TWJW-SANGER** [comment]
Danni has pointed out I was wrong initially about the "Scan In / Out" preventing this from happening.

It is also possible to do this by using the "Scan In / Out" and copying in a location barcode.

Should we fix this though, it should be consistent across the pages.

**Comment by TWJW-SANGER** [comment]
From Danni:
_Yes this is something I would like prevented, it happens often enough that I will routinely need to email Neil to removed them from labwhere._

**Comment by harrietc52** [comment]
Tasks
- add another validation method to ManifestUploader
- Validation method: 
- Nil check CSV data
- Loop through every row in the CSV data; check "Labware" entry (barcode) isn't the same and any existing Location name
- If not valid; Fail upload and return all labware entry barcodes which are duplicates in an error message
- If valid; continue
