### ISSUE TITLE
GPL-794 Register robot serials as users in labwhere

### ISSUE THREAD

**Issue by JamesGlover** [sanger/labwhere#271]
**User story**
When lighthouse updates source-plate locations automatically it uses the robot barcode/serial number. These robots will need to be registered in labwhere as users.

Example codes logged so far:
B8758420K09
B8758420K10

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
Need to have logged the following robots:
- [x] B8758420K09 (HERON-CP3)
- [x] B8758420K10 (HERON-CP4)
- [x] B8758420K08 (HERON-CP1)
- [x] B8758420K07 (HERON-CP2)

**Comment by KatyTaylor** [comment]
From Mike a while ago:
![view_robot_status 1 - all robots running](https://user-images.githubusercontent.com/10407809/103760448-098d8a80-500d-11eb-8ebb-abe6a7bd8da4.PNG)

**Comment by stevieing** [comment]
Closed as project finished.
