### ISSUE TITLE
GPL-798: BUG - As a sample management manager I would like to see an error message when I try to move a location into a building

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#281]
**Describe the bug**
BUG - As a sample management manager I would like to see an error message when I try to move a location into a building as it is not a container.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by BenTopping** [comment]
- [] move_location_form add a check to see if parent location type is a building
