### ISSUE TITLE
GPL-814-2 As a developer I would like to move LabWhere to HTTPS [Strategic]

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#297]
**User story**
At the moment Labwhere is on http and I would like it to be on https for a better level of security.

**Who are the primary contacts for this story**
Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] implement https https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Migrate+a+Rails+App+from+HTTP+-%3E+HTTPS 
- [ ] move admin passwords to the vault (is this the admin barcode and swipe_card_id in the rake task?)

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by harrietc52** [comment]
Implemented via https://github.com/sanger/deployment/issues/28

**Comment by stevieing** [comment]
Closed as done.
