### ISSUE TITLE
GPL-831 - As heron lab users we need to be able to print barcodes to the Squix printers

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#305]
**User story**
As heron lab users we need to be able to print barcodes to the Squix printers

**Who are the primary contacts for this story**
Danni

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by harrietc52** [comment]
Lucid Charts:
https://lucid.app/lucidchart/invitations/accept/863d895a-3889-4afd-bc64-67ddf4bcc593
https://lucid.app/lucidchart/invitations/accept/45c0e45b-d26b-4765-a13b-2d303c00f68d

**Comment by harrietc52** [comment]
The label templates should be the exact same as the existing templates from PMB

**Comment by harrietc52** [comment]
**Notes before merge/ deploy**
Merge deployment branch PR sanger/deployment#12 (from https://github.com/sanger/print_my_barcode/issues/66)
On deployment run: `Printer.all.each { |p| p.update_attributes!(printer_type: :toshiba) }` to add printer type Toshiba to all existing Printers

**Comment by harrietc52** [comment]
- [ ] GPL-831-1
- [ ] GPL-831-2
- [ ] GPL-831-3
- [ ] GPL-831-4

**Comment by harrietc52** [comment]
- [ ] remove Printer modal from LabWhere? get Printers with Type from PMB via v2 api. Show this list of printers in Locations/new/prints form. Check all where using Printer modal
- [ ] update create method. Check printer, if type Toshiba, send print job to v1, if squix send print job to v2. Move wrapper from PMB?
- [ ] 1D/ 2D barcodes? How does this relate to the label template. Are both available for both Toshiba/ Squix printer types?
- [ ] Supporting Child Barcodes for both Squix and Toshiba?
