### ISSUE TITLE
GPL-831-3 As a developer I need to create a label template for 2D and code128 barcodes

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#311]
**User story**
GPL-nnn As a developer I need to create a label template for 2D barcode (datamatrix), and Code128

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] In Labwhere I should be able to print 2D barcodes to Squix printers
- [ ]  In Labwhere I should be able to select printing a code128 barcode

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by harrietc52** [comment]
Comments from -5 relevent for this story
The label templates should have same names as Toshiba label templates
The templates should be human readable
The templates should be stored in the deployment project (sprint role)

**Comment by stevieing** [comment]
Closed as done.
