### ISSUE TITLE
GPL-880 - As a reefer manager I would like a report on the status of the reefers to find out where the most free space is [Heron]

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#321]
**User story**
As a reefer manager I would like a report on the status of the reefers to find out where the most free space is

priority: 1

**Who are the primary contacts for this story**
Bart

**Acceptance criteria**
To be considered successful the solution must allow. The report would tell me:
- [ ] how much empty space is in each reefer
- [ ] how much empty space is in each shelf and rack
- [ ] what boxes are currently stored on each rack

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by TWJW-SANGER** [comment]
FYI There is a Tableau report that shows the current empty space of the reefers at the bottom of the page here:
https://globalreporting.internal.sanger.ac.uk/#/views/LabWhere/LighthouseStorageDestruction?:iid=1

(Might cover the first use case).

**Comment by stevieing** [comment]
> FYI There is a Tableau report that shows the current empty space of the reefers at the bottom of the page here:
> https://globalreporting.internal.sanger.ac.uk/#/views/LabWhere/LighthouseStorageDestruction?:iid=1
> 
> (Might cover the first use case).

Thanks Tom. That is useful. Bart requires more information than the amount of empty space but it might be useful as an interm solution so he can have a quick look.

**Comment by rl15** [comment]
Bart Siwek wrote (Monday, 15 March 2021 at 15:27)

we have tableau view: https://globalreporting.internal.sanger.ac.uk/#/views/LabWhere/LighthouseStorageDestruction?:iid=1 – what is this missing that requires feature in LabWhere?
Yes, this report is sufficient

**Comment by stevieing** [comment]
Closed as no longe needed.
