### ISSUE TITLE
GPL-961 BUG - Errors not handled gracefully when messages can't be sent.

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#363]
**Describe the bug**
hat happened is: monit saw that labwhere could not connect to rabbitmq and restarted
4:00
when restarted it, labwhere could not connect! at all and that broke the app
4:01
so we need to add a way of handling that start for labwhere: if there is no connection, then don't connect to the queues
4:01
that is why labwhere stopped working at 3:30, not because of losing connection, but because it cannot start the first time without having rabbitmq running

Solution:
- add a rescue when labwhere tries to connect and send an email

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
Labwhere should carry on working.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by rl15** [comment]
Rich L: Looking at GPL-961 was surprised you wanted notification by email not slack?

Team: Pragmatic decision. We are using the exception notifier and it is already setup for email. Just raised it in stand up and that was the consensus. We can always add slack support later as the exception notifier supports it.

**Comment by emrojo** [comment]
Ideas to test in UAT:

1. Test that you can scan new barcodes and the instance of Labwhere can trigger creating a new record in the warehouse (there is RabbitMQ connection)
2. Add a temporal network route in the machine to lose connectivity with RabbitMQ
3. Test that you can still scan new barcodes (check that there is no new records in the warehouse)
4. Restart Labwhere with monit
5. Test that you can scan new barcodes (check that there is no new records in the warehouse)
4. Remove the route
5. Test that you can scan new barcodes and that the warehouse receives messages

**Comment by emrojo** [comment]
Add the route (block connection):
route add -host <server> dev lo

Remove the route (allow connection):
route del -host <server> dev lo

connection_timeout gives a number of secods to try connecting. Defaults to 30 seconds, but it will be triggered for each labware in the list. 
Options could be: decreasing the value (2-3 seconds), or create the connection and publish in a different thread than the web server to not block the request for too long (after 60 seconds the request will fail with a 500).
```
      @connection = Bunny.new host: bunny_config.broker_host,
                              port: bunny_config.broker_port,
                              username: bunny_config.broker_username,
                              password: bunny_config.broker_password,
                              connection_timeout: 2,
                              vhost: bunny_config.vhost
```
