### ISSUE TITLE
DPL-082 Add a new endpoint to upload box manifests

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#412]
**User story**
We have a Sample Prioritisation pipeline awaiting final sign off for production use. This pipeline is entirely automated except for one step. That step is the box manifest upload. This is critical as the pipeline only considers samples on plates in boxes that had their manifest uploaded on that day. Currently, this upload is handled by Bart Siwek’s team for a deadline of 8:30. However, we wish to move the pipeline execution earlier as lab staff want the results to be guaranteed to be visible in box buster by 8:45 and we cannot guarantee this with the current timings of the selection logic and webcrawler. We cannot expect Bart’s team to come in and upload the box manifests at an earlier time so the solution is to automate the process. To do that, we would need an API to submit box manifests to.

In addition, there has been a new demand to prioritise sequencing of specially marked plates containing red list travel samples from Milton Keynes. This cannot be implemented without automating the box manifest process, requesting additional data from NHSD or modifying MLWH to include data on which plates are labelled as high priority (which would require a change to the box manifest upload system anyway to accomadate this additional information).

**Who are the primary contacts for this story**
e.g. Rhys, Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] We would like the end point to accept a json file (format in comments)
- [x] If the call is successful a success message will be returned
- [x] if the call fails a failure message will be returned which will include details of the errors
- [x] The call should be performant - to be agreed?
- [x] The event that should be triggered is uploaded_from_manifest
- [x] The call should be authenticated in the body

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
This is a placeholder. Will wait on email from Rhys to update and then add acceptance criteria.

**Comment by stevieing** [comment]
endpoint: /api/upload_labwares [POST, contentType: application/json]

payload:

{
 labwares: [
{ location_barcode: 'loc-1', labware_barcode: 'DN1'},
...
]
}

To decide:
- is this the best name for the endpoint? We are just creating labware so maybe it should just be /api/labwares/

**Comment by KatyTaylor** [comment]
From Heron sample prioritisation meeting today - 

Rhys is expecting to start on his part of this feature ~Mon 2nd, expecting it to be a week (so Mon 9th) before he is ready to start using this endpoint.

Tanya set a target of go-live by 20th August.

**Comment by harrietc52** [comment]
API Documentation https://uat.labwhere.psd.sanger.ac.uk/api/docs Labwares > Create Labwares
