### ISSUE TITLE
DPL-262 - As SM I would like to delete empty locations and remove them from the ui (C=S, V=3)

### ISSUE THREAD

**Issue by stevieing** [sanger/labwhere#473]
**User story**
As SM I would like to delete empty locations and remove them from the ui (C=S, V=3)

**Who are the primary contacts for this story**
Danni

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] A location deletion option in the drop down menu
- [ ] deletion of multiple locations at the same time
- [ ] A search option for locations to delete
- [ ] deletion of locations which are empty only (the page will only show empty locations)
- [ ] locations with an audit history will be set to inactive
- [ ] Whether the location has been deleted or inactive will be transparent to the user i.e it will be done as a single action.
- [ ] Hiding of inactive locations from the user

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
RT736218

**Comment by dw15sanger** [comment]
Hilariously I can't remember why I requested this story, is this related to the empty locations? I think users would want to be able to see empty locations, I have no idea why I requested this story!

**Comment by stevieing** [comment]
> Hilariously I can't remember why I requested this story, is this related to the empty locations? I think users would want to be able to see empty locations, I have no idea why I requested this story!

Currently you can still see inactive locations in the ui. You will still be able to see empty locations. It is a way of soft deleting locations whilst still being able to see the audit history.

**Comment by Danniw373** [comment]
I don't quite understand, do you have 5/10 mins this week to show me? It will probably be easier/quicker that way!
