### ISSUE TITLE
DPL-758	Unable to create rooms

### ISSUE THREAD

**Issue by neilsycamore** [sanger/labwhere#649]
As a LabWhere user (admin, technician) I am unable to create a room
**RT Ticket Number**
777360

Selection of the parent is REALLY slow, when  clicking on 'Create location' there is a delay then goes thru the following stages. 
<img width="1512" alt="Screenshot 2023-04-25 at 13 08 09" src="https://user-images.githubusercontent.com/299768/234812762-79dde9b0-66e5-4089-93e5-774f7678059e.png">
<img width="1512" alt="Screenshot 2023-04-25 at 13 08 15" src="https://user-images.githubusercontent.com/299768/234812898-9af057fd-dc61-473b-8045-7a5192861a5b.png">
Javascript console output
![Screenshot 2023-04-25 at 13 27 04](https://user-images.githubusercontent.com/299768/234813156-86391c8d-ad80-463f-ba5c-a0b6f8602de0.png)
It s also not possible to update the protected status of the room in the app, there is no yes or no validation response when doing so.

**Comment by SujitDey2022** [comment]
@neilsycamore I was reviewing this bug and wanted to check if we have an understanding of the errors shown and the expected outcome or if is this something that needs to be investigated and discussed further with the stakeholder.

**Comment by harrietc52** [comment]
## Findings

### Current versions deployed

LabWhere WIP [uat] 20230404145150 [master@b376dcb](https://github.com/sanger/labwhere/releases/tag/v1.21.0)

LabWhere WIP [training] 20230404151344 [master@b376dcb](https://github.com/sanger/labwhere/releases/tag/v1.21.0)

LabWhere WIP [production] 20230315180010 [master@b376dcb](https://github.com/sanger/labwhere/releases/tag/v1.21.0)

These are all from Release version 1.21.0, from the Ruby 3 upgrade.

**Comment by harrietc52** [comment]
Deployed to prod in release [1.22.0](https://github.com/sanger/labwhere/releases/tag/v1.22.0)
