### ISSUE TITLE
Y24-156 - [BUG] Re-editing of a location name is needed if a longer name is required

### ISSUE THREAD

**Issue by seenanair** [sanger/labwhere#796]
**Describe the bug**
When creating a storage location, it is required to first enter a short name for the storage location so that it fits on printed barcodes. Then it needs to be re-edited to a longer, more descriptive name if needed. Many people struggle with it in the lab, and it takes much more effort.

**Expected behaviour**
It should allow the user to enter the required name while creating, without the need for re-editing

**Additional context**
Discuss with the stakeholder(Tristram Bellerby) to check whether there is a possibility of switching to 2D barcodes.
or
Keeping separate fields for printing and display

**Comment by KatyTaylor** [comment]
Extra info: 

I think behind the scenes this is because when you first save the location name, it uses that to create the 'barcode' in the system. Subsequent edits have no effect on the barcode.

**Comment by SHIV5T3R** [comment]
After speaking to stakeholders, this story is now back on hold.

It seems that some users in some teams are unable to upgrade to 2D barcode scanners (budget apparently) which would mean we'd need to do extra work to keep supporting 1D barcodes (while resolving issues that they have). The solution suggested by Danni would be to notify users that a location name is too long to fit on a label with a 1D barcode, which doesn't resolve the issue described in this story.

@SujitDey2022 @stevieing

**Comment by stevieing** [comment]
Closed as no longer needed. Leaving it here is confusing the issue. We can always reopen it.
